# Generated by Django 3.1.5 on 2021-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=112)),
                ('firstname', models.CharField(max_length=112)),
                ('lastname', models.CharField(max_length=112)),
                ('email', models.CharField(max_length=112)),
                ('phone', models.CharField(max_length=12)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('website', models.CharField(max_length=112)),
                ('instagram', models.CharField(max_length=112)),
                ('facebook', models.CharField(max_length=112)),
                ('twitter', models.CharField(max_length=112)),
                ('otherlinks', models.TextField()),
                ('highlight', models.TextField()),
            ],
        ),
    ]
