# Generated by Django 3.1.5 on 2021-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='facebook',
            field=models.CharField(default='', max_length=112),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='highlight',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='image',
            field=models.ImageField(upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='instagram',
            field=models.CharField(default='', max_length=112),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='otherlinks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='twitter',
            field=models.CharField(default='', max_length=112),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='website',
            field=models.CharField(default='', max_length=112),
        ),
    ]
