# Generated by Django 3.1.5 on 2021-01-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210122_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='image',
            new_name='Image',
        ),
    ]
