# Generated by Django 3.1.5 on 2021-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='Image',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='pic',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
