# Generated by Django 3.1.5 on 2021-01-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210122_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='text',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='pic',
        ),
    ]
