# Generated by Django 3.1.5 on 2021-01-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210122_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='pic',
            field=models.ImageField(default='', upload_to='profiles'),
        ),
    ]
