# Generated by Django 3.1.5 on 2021-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210124_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2021)),
                ('month', models.IntegerField(default=3)),
                ('prev', models.IntegerField(default=0)),
                ('w1', models.IntegerField(default=0)),
                ('w2', models.IntegerField(default=0)),
                ('w3', models.IntegerField(default=0)),
                ('w4', models.IntegerField(default=0)),
            ],
        ),
    ]
