# Generated by Django 3.1.5 on 2021-03-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_analytic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
